// ═══════════════════════════════════════════════════════════
//  NEXUS — Intent Detection
//  تشخیص دستورات فارسی/انگلیسی
// ═══════════════════════════════════════════════════════════

export function detectIntent(text) {
  if (!text) return null;
  const t = text.toLowerCase().trim();
  const first = t.split(/\s+/)[0].replace(/@\w+/, '');
  const map = {
    '/start': 'start', 'استارت': 'start', 'شروع': 'start', 'start': 'start',
    '/help': 'help', 'راهنما': 'help', 'کمک': 'help', 'help': 'help',
    '/ping': 'ping', 'پینگ': 'ping', 'ping': 'ping',
    '/id': 'id', 'آیدی': 'id', 'ایدی': 'id',
    '/settings': 'settings', '/panel': 'settings', 'تنظیمات': 'settings', 'پنل': 'settings', 'settings': 'settings',
    '/stats': 'stats', 'آمار': 'stats', 'stats': 'stats',
    '/dashboard': 'dashboard', 'داشبورد': 'dashboard', 'پنل وب': 'dashboard',
    '/ban': 'ban', 'بن': 'ban', 'ban': 'ban',
    '/unban': 'unban', 'آنبن': 'unban', 'unban': 'unban',
    '/mute': 'mute', 'میوت': 'mute', 'ساکت': 'mute', 'mute': 'mute',
    '/unmute': 'unmute', 'آنمیوت': 'unmute', 'آزاد': 'unmute', 'unmute': 'unmute',
    '/kick': 'kick', 'کیک': 'kick', 'اخراج': 'kick', 'kick': 'kick',
    '/warn': 'warn', 'اخطار': 'warn', 'warn': 'warn',
    '/unwarn': 'unwarn', 'unwarn': 'unwarn',
    '/warns': 'warns', 'اخطارها': 'warns',
    '/purge': 'purge', 'پاکسازی': 'purge', 'purge': 'purge',
    '/del': 'del', 'حذف': 'del', 'del': 'del',
    '/admins': 'admins', 'ادمین‌ها': 'admins', 'ادمینها': 'admins', 'مدیران': 'admins', 'لیست ادمین': 'admins',
    '/rules': 'rules', 'قوانین': 'rules', 'rules': 'rules', 'قانون': 'rules',
    '/notes': 'listnotes', 'یادداشت‌ها': 'listnotes',
    '/cancel': 'cancel', 'لغو': 'cancel', 'cancel': 'cancel',
    '/profile': 'profile', 'پروفایل': 'profile', 'profile': 'profile',
    '/rank': 'profile', 'رتبه': 'profile', 'level': 'profile', 'سطح': 'profile',
    '/leaderboard': 'leaderboard', 'top': 'leaderboard', 'برترین‌ها': 'leaderboard',
    '/lb': 'leaderboard', 'لیدربورد': 'leaderboard',
    '/achievements': 'achievements', 'دستاوردها': 'achievements',
    '/games': 'games', 'بازی': 'games', 'بازی‌ها': 'games', 'games': 'games',
    '/guess': 'guess', 'حدس': 'guess',
    '/rps': 'rps',
    '/slot': 'slot', 'اسلات': 'slot',
    '/quiz': 'quiz', 'مسابقه': 'quiz',
    '/dice': 'dice', 'تاس': 'dice',
    '/type': 'type', 'تایپ': 'type',
    '/ai': 'ai', 'هوش': 'ai',
    '/settitle': 'settitle', 'لقب': 'settitle', 'عنوان': 'settitle', 'settitle': 'settitle',
    '/promote': 'promote', 'ارتقا': 'promote', 'ادمین کن': 'promote', 'promote': 'promote',
    '/demote': 'demote', 'تنزل': 'demote', 'عزل': 'demote', 'demote': 'demote',
    '/report': 'report', 'گزارش': 'report', 'ریپورت': 'report', 'report': 'report',
    '/poll': 'poll', 'نظرسنجی': 'poll', 'poll': 'poll',
    '/schedule': 'schedule', 'زمان‌بندی': 'schedule', 'schedule': 'schedule',
    '/schedules': 'schedules', 'لیست زمان‌بندی': 'schedules',
    '/unschedule': 'unschedule', 'حذف زمان‌بندی': 'unschedule',
    '+rep': 'plusrep', 'اعتبار+': 'plusrep',
    '-rep': 'minusrep', 'اعتبار-': 'minusrep',
    '/rep': 'reptop', 'اعتبارات': 'reptop', 'تاپ اعتبار': 'reptop',
    '/invites': 'invites', 'دعوت‌ها': 'invites',
    '/shutup': 'shutup', 'سکوت ربات': 'shutup',
    '/fed': 'fed', 'فدراسیون': 'fed',
    '/newfed': 'newfed', 'فدراسیون جدید': 'newfed',
    '/joinfed': 'joinfed', 'ورود فدراسیون': 'joinfed',
    '/leavefed': 'leavefed', 'خروج فدراسیون': 'leavefed',
    '/fedban': 'fedban', 'بن فدرال': 'fedban',
    '/fedunban': 'fedunban', 'آنبن فدرال': 'fedunban',
    '/fedbans': 'fedbans', 'لیست بن فدرال': 'fedbans',
    '/gban': 'gban', 'بن سراسری': 'gban',
    '/ungban': 'ungban', 'آنبن سراسری': 'ungban',
    '/gbans': 'gbans', 'لیست بن سراسری': 'gbans',
    '/backup': 'backup', 'پشتیبان': 'backup',
    '/restore': 'restore', 'بازیابی': 'restore',
    '/setlang': 'setlang', 'زبان': 'setlang',
    '/dban': 'dban', 'dبن': 'dban',
    '/dkick': 'dkick', 'dکیک': 'dkick',
    '/dmute': 'dmute', 'dمیوت': 'dmute',
    '/dwarn': 'dwarn', 'dاخطار': 'dwarn',
    '/sban': 'sban', '/skill': 'skill', '/smute': 'smute', '/swarn': 'swarn',
    '/alias': 'alias', 'نام‌گذاری': 'alias',
    '/unalias': 'unalias', 'حذف نام': 'unalias',
    '/aliases': 'aliases', 'لیست نام‌ها': 'aliases',
    '/warnchain': 'warnchain', 'زنجیره اخطار': 'warnchain',
    '/perms': 'perms', 'دسترسی‌ها': 'perms',
    '/scheddaily': 'scheddaily', 'زمان‌بندی روزانه': 'scheddaily',
    '/langblock': 'langblock', 'فیلتر زبان': 'langblock',
    '/search': 'search', 'جستجو': 'search',
    '/screen': 'screen', 'بررسی عمیق': 'screen',
    '/price': 'price', 'قیمت': 'price', 'نرخ': 'price',
    '/anime': 'anime', 'انیمه': 'anime',
    '/sync': 'sync', 'همگام': 'sync',
    '/silent': 'silent', 'بی‌صدا': 'silent',
    '/pin': 'pin', 'پین کن': 'pin',
    '/unpin': 'unpin', 'آنپین': 'unpin',
    '/ghost': 'ghost', 'پاکسازی کش': 'ghost',
    '/status': 'status', 'وضعیت': 'status',
    '/confirm': 'confirm', 'تایید': 'confirm',
  };
  return map[first] || null;
}
